USE [master]
GO
/****** Object:  Database [BasicDb]    Script Date: 12-02-2026 13:11:47 ******/
CREATE DATABASE [BasicDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BasicDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BasicDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BasicDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\BasicDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BasicDb] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BasicDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BasicDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BasicDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BasicDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BasicDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BasicDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [BasicDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BasicDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BasicDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BasicDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BasicDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BasicDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BasicDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BasicDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BasicDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BasicDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BasicDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BasicDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BasicDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BasicDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BasicDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BasicDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BasicDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BasicDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BasicDb] SET  MULTI_USER 
GO
ALTER DATABASE [BasicDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BasicDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BasicDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BasicDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BasicDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BasicDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BasicDb] SET QUERY_STORE = ON
GO
ALTER DATABASE [BasicDb] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BasicDb]
GO
/****** Object:  Table [dbo].[RefreshTokens]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RefreshTokens](
	[RefreshTokenId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NOT NULL,
	[Token] [nvarchar](500) NOT NULL,
	[ExpiryDate] [datetime2](7) NOT NULL,
	[IsRevoked] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[RefreshTokenId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](50) NOT NULL,
	[Password] [text] NOT NULL,
	[Role] [nvarchar](10) NOT NULL,
	[CreatedBy] [int] NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedBy] [int] NULL,
	[updatedOn] [datetime] NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[RefreshTokens] ADD  DEFAULT ((0)) FOR [IsRevoked]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT ((0)) FOR [IsDeleted]
GO
ALTER TABLE [dbo].[RefreshTokens]  WITH CHECK ADD  CONSTRAINT [FK_RefreshTokens_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[RefreshTokens] CHECK CONSTRAINT [FK_RefreshTokens_Users]
GO
/****** Object:  StoredProcedure [dbo].[sp_GetRefreshToken]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_GetRefreshToken]
    @Token NVARCHAR(500)
AS
BEGIN
    SELECT *
    FROM RefreshTokens
    WHERE Token = @Token
END
GO
/****** Object:  StoredProcedure [dbo].[sp_RevokeRefreshToken]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_RevokeRefreshToken]
    @Token NVARCHAR(500)
AS
BEGIN
    UPDATE RefreshTokens
    SET IsRevoked = 1
    WHERE Token = @Token
END
GO
/****** Object:  StoredProcedure [dbo].[sp_SaveRefreshToken]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_SaveRefreshToken]
    @UserId INT,
    @Token NVARCHAR(500),
    @Expiry DATETIME2
AS
BEGIN
    INSERT INTO RefreshTokens (UserId, Token, ExpiryDate)
    VALUES (@UserId, @Token, @Expiry)
END
GO
/****** Object:  StoredProcedure [dbo].[sp_User_Create]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[sp_User_Create]
    @Username NVARCHAR(100),
    @Password NVARCHAR(500),
    @Role NVARCHAR(50),
    @CreatedBy int,
    @CreatedOn Datetime
AS
BEGIN
    INSERT INTO Users
    (
        Username,
        Password,
        Role,
        CreatedBy,
        CreatedOn
    )
    VALUES
    (
        @Username,
        @Password,
        @Role,
        @CreatedBy,
        @CreatedOn
    );

    SELECT SCOPE_IDENTITY();
END
GO
/****** Object:  StoredProcedure [dbo].[sp_User_Delete]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[sp_User_Delete]
    @Id INT
AS
BEGIN
    UPDATE Users
    SET 
        IsDeleted = 1
    WHERE UserId = @Id
END
GO
/****** Object:  StoredProcedure [dbo].[sp_User_GetAll]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[sp_User_GetAll]
AS
BEGIN
    SELECT UserId, Username, Role, CreatedOn
    FROM Users where IsDeleted=0
END
GO
/****** Object:  StoredProcedure [dbo].[sp_User_Update]    Script Date: 12-02-2026 13:11:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[sp_User_Update]
    @Id INT,
    @Username NVARCHAR(100),
    @Role NVARCHAR(50),
    @UpdatedBy INT,
	@UpdatedOn Datetime
AS
BEGIN
    UPDATE Users
    SET 
        Username = @Username,
        Role = @Role,
        UpdatedBy = @UpdatedBy,
        UpdatedOn = @UpdatedOn
    WHERE UserId = @Id
END
GO
USE [master]
GO
ALTER DATABASE [BasicDb] SET  READ_WRITE 
GO
